apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      namespace: chat-app
      labels: 
        app: frontend
    spec:
      containers:
      - name: frontend
        image: madhul423/devops-frontend:<commit-sha>
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: production
          


