name: DevOps CI/CD Pipeline

on:
  push:
    branches: ["main"]

env:
  BACKEND_IMAGE: madhul423/devops-backend
  FRONTEND_IMAGE: madhul423/devops-frontend
  TF_VERSION: 1.6.6

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:

    # 1️⃣ Checkout
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 2️⃣ Docker Login
    - name: Login DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3️⃣ Build Backend
    - name: Build Backend
      run: docker build -t $BACKEND_IMAGE:${{ github.sha }} -f backend/Dockerfile backend

    # 4️⃣ Scan Backend
    - name: Scan Backend Image
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: ${{ env.BACKEND_IMAGE }}:${{ github.sha }}
        severity: CRITICAL,HIGH
        exit-code: 1
        ignore-unfixed: true

    # 5️⃣ Push Backend
    - name: Push Backend
      run: docker push $BACKEND_IMAGE:${{ github.sha }}

    # 6️⃣ Build Frontend
    - name: Build Frontend
      run: docker build -t $FRONTEND_IMAGE:${{ github.sha }} -f frontend/Dockerfile frontend

    # 7️⃣ Scan Frontend
    - name: Scan Frontend Image
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
        severity: CRITICAL,HIGH
        exit-code: 1
        ignore-unfixed: true

    # 8️⃣ Push Frontend
    - name: Push Frontend
      run: docker push $FRONTEND_IMAGE:${{ github.sha }}

    # 9️⃣ Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    # 🔟 Terraform Init
    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    # 1️⃣1️⃣ Terraform Apply
    - name: Terraform Apply
      working-directory: terraform
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # 1️⃣2️⃣ Get EC2 IP
    - name: Get Server IP
      id: tf_output
      working-directory: terraform
      run: |
        echo "ip=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT

    # 1️⃣3️⃣ Setup SSH
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/key.pem
        chmod 600 ~/.ssh/key.pem

    # 1️⃣4️⃣ Install Ansible
    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    # 1️⃣5️⃣ Add EC2 to known hosts
    - name: Add EC2 to known hosts
      run: |
        ssh-keyscan -H ${{ steps.tf_output.outputs.ip }} >> ~/.ssh/known_hosts

    # 1️⃣6️⃣ Deploy via Ansible
    - name: Deploy to Minikube
      run: |
        ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook \
        -i "${{ steps.tf_output.outputs.ip }}," \
        --private-key ~/.ssh/key.pem \
        -u ubuntu \
        -e "image_tag=${{ github.sha }}" \
        -e "jwt_secret=${{ secrets.JWT_SECRET }}" \
        ansible/deploy.yml